# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'glDesignMW.ui'
#
# Created: Thu Jan 11 11:00:18 2018
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(744, 565)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 741, 511))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabGuteLuft = QtGui.QWidget()
        self.tabGuteLuft.setObjectName(_fromUtf8("tabGuteLuft"))
        self.label = QtGui.QLabel(self.tabGuteLuft)
        self.label.setGeometry(QtCore.QRect(10, 10, 391, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Bitstream Charter"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_3 = QtGui.QLabel(self.tabGuteLuft)
        self.label_3.setGeometry(QtCore.QRect(230, 44, 111, 18))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.TestLabel = QtGui.QLabel(self.tabGuteLuft)
        self.TestLabel.setGeometry(QtCore.QRect(350, 42, 191, 18))
        self.TestLabel.setObjectName(_fromUtf8("TestLabel"))
        self.label_2 = QtGui.QLabel(self.tabGuteLuft)
        self.label_2.setGeometry(QtCore.QRect(10, 42, 191, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Bitstream Charter"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.pushButton = QtGui.QPushButton(self.tabGuteLuft)
        self.pushButton.setGeometry(QtCore.QRect(100, 102, 100, 27))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.comboBox = QtGui.QComboBox(self.tabGuteLuft)
        self.comboBox.setGeometry(QtCore.QRect(10, 62, 191, 21))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.verticalLayoutWidget = QtGui.QWidget(self.tabGuteLuft)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(230, 80, 491, 381))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.layout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.layout.setMargin(0)
        self.layout.setObjectName(_fromUtf8("layout"))
        self.tabWidget.addTab(self.tabGuteLuft, _fromUtf8(""))
        self.TabCO2Ampel = QtGui.QWidget()
        self.TabCO2Ampel.setObjectName(_fromUtf8("TabCO2Ampel"))
        self.label_4 = QtGui.QLabel(self.TabCO2Ampel)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 391, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Bitstream Charter"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.TabCO2Ampel)
        self.label_5.setGeometry(QtCore.QRect(320, 50, 371, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Bitstream Charter"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.TabCO2Ampel)
        self.label_6.setGeometry(QtCore.QRect(20, 80, 211, 181))
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.pushButtonControlCO2Ampel = QtGui.QPushButton(self.TabCO2Ampel)
        self.pushButtonControlCO2Ampel.setGeometry(QtCore.QRect(20, 280, 211, 27))
        self.pushButtonControlCO2Ampel.setObjectName(_fromUtf8("pushButtonControlCO2Ampel"))
        self.tabWidget.addTab(self.TabCO2Ampel, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 744, 28))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMain = QtGui.QMenu(self.menubar)
        self.menuMain.setObjectName(_fromUtf8("menuMain"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSave_Image = QtGui.QAction(MainWindow)
        self.actionSave_Image.setObjectName(_fromUtf8("actionSave_Image"))
        self.actionProvide_feedback = QtGui.QAction(MainWindow)
        self.actionProvide_feedback.setObjectName(_fromUtf8("actionProvide_feedback"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionWindowActionTest = QtGui.QAction(MainWindow)
        self.actionWindowActionTest.setObjectName(_fromUtf8("actionWindowActionTest"))
        self.actionWindowActionCombo = QtGui.QAction(MainWindow)
        self.actionWindowActionCombo.setObjectName(_fromUtf8("actionWindowActionCombo"))
        self.menuMain.addAction(self.actionSave_Image)
        self.menuMain.addAction(self.actionProvide_feedback)
        self.menuAbout.addAction(self.actionAbout)
        self.menubar.addAction(self.menuMain.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "guteluft.jade-hs.de", None))
        self.label.setText(_translate("MainWindow", "This section is to view a data of guteluft.jade-hs.de", None))
        self.label_3.setText(_translate("MainWindow", "Chosen room:", None))
        self.TestLabel.setText(_translate("MainWindow", "____", None))
        self.label_2.setText(_translate("MainWindow", "Chose the room:", None))
        self.pushButton.setText(_translate("MainWindow", "Get help!", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "H-I-07", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "H-I-10", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "H-I-21", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGuteLuft), _translate("MainWindow", "guteluft.jade-hs.de", None))
        self.label_4.setText(_translate("MainWindow", "This section is to view a data of CO2-Ampel", None))
        self.label_5.setText(_translate("MainWindow", "We will visualize here live the data of CO2-Ampel(Logger)", None))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\">We will train here to control Device via Tango. For training aims, the MySQL Tango-Database must be configured on controlled computer, Tango Server must run on it too and &quot;Tango Device Server&quot; - just Raspberry controlling LEDS must run on it too. </p></body></html>", None))
        self.pushButtonControlCO2Ampel.setText(_translate("MainWindow", "Test \"Control Device\"", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TabCO2Ampel), _translate("MainWindow", "CO2-Ampel", None))
        self.menuMain.setTitle(_translate("MainWindow", "Main", None))
        self.menuAbout.setTitle(_translate("MainWindow", "About", None))
        self.actionSave_Image.setText(_translate("MainWindow", "Save Image", None))
        self.actionProvide_feedback.setText(_translate("MainWindow", "Provide feedback", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionWindowActionTest.setText(_translate("MainWindow", "WindowActionTest", None))
        self.actionWindowActionCombo.setText(_translate("MainWindow", "WindowActionCombo", None))

