# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'glDesignMW.ui'
#
# Created: Fri Jan 12 17:02:46 2018
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(863, 721)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1451, 121))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tabGuteLuft = QtGui.QWidget()
        self.tabGuteLuft.setObjectName(_fromUtf8("tabGuteLuft"))
        self.label = QtGui.QLabel(self.tabGuteLuft)
        self.label.setGeometry(QtCore.QRect(10, 10, 391, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Bitstream Charter"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.tabGuteLuft)
        self.label_2.setGeometry(QtCore.QRect(10, 42, 191, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Bitstream Charter"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.comboBox = QtGui.QComboBox(self.tabGuteLuft)
        self.comboBox.setGeometry(QtCore.QRect(10, 62, 191, 21))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.pushButton = QtGui.QPushButton(self.tabGuteLuft)
        self.pushButton.setGeometry(QtCore.QRect(360, 10, 100, 27))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.tabWidget.addTab(self.tabGuteLuft, _fromUtf8(""))
        self.TabCO2Ampel = QtGui.QWidget()
        self.TabCO2Ampel.setObjectName(_fromUtf8("TabCO2Ampel"))
        self.label_4 = QtGui.QLabel(self.TabCO2Ampel)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 391, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Bitstream Charter"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_6 = QtGui.QLabel(self.TabCO2Ampel)
        self.label_6.setGeometry(QtCore.QRect(330, 0, 481, 91))
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.pushButtonControlCO2Ampel = QtGui.QPushButton(self.TabCO2Ampel)
        self.pushButtonControlCO2Ampel.setGeometry(QtCore.QRect(10, 40, 211, 27))
        self.pushButtonControlCO2Ampel.setObjectName(_fromUtf8("pushButtonControlCO2Ampel"))
        self.tabWidget.addTab(self.TabCO2Ampel, _fromUtf8(""))
        self.checkBoxTemperatur = QtGui.QCheckBox(self.centralwidget)
        self.checkBoxTemperatur.setGeometry(QtCore.QRect(20, 121, 131, 23))
        self.checkBoxTemperatur.setChecked(True)
        self.checkBoxTemperatur.setObjectName(_fromUtf8("checkBoxTemperatur"))
        self.checkBoxHumidity = QtGui.QCheckBox(self.centralwidget)
        self.checkBoxHumidity.setGeometry(QtCore.QRect(20, 151, 101, 23))
        self.checkBoxHumidity.setChecked(True)
        self.checkBoxHumidity.setObjectName(_fromUtf8("checkBoxHumidity"))
        self.labelInfo = QtGui.QLabel(self.centralwidget)
        self.labelInfo.setGeometry(QtCore.QRect(30, 180, 251, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Bitstream Charter"))
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelInfo.setFont(font)
        self.labelInfo.setObjectName(_fromUtf8("labelInfo"))
        self.verticalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 210, 831, 441))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.layout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.layout.setContentsMargins(-1, -1, 0, -1)
        self.layout.setObjectName(_fromUtf8("layout"))
        self.LabelInfo = QtGui.QLabel(self.centralwidget)
        self.LabelInfo.setGeometry(QtCore.QRect(280, 180, 191, 18))
        self.LabelInfo.setObjectName(_fromUtf8("LabelInfo"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 863, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuMain = QtGui.QMenu(self.menubar)
        self.menuMain.setObjectName(_fromUtf8("menuMain"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.submenuProvideFeedback = QtGui.QAction(MainWindow)
        self.submenuProvideFeedback.setObjectName(_fromUtf8("submenuProvideFeedback"))
        self.submenuAbout = QtGui.QAction(MainWindow)
        self.submenuAbout.setObjectName(_fromUtf8("submenuAbout"))
        self.menuMain.addAction(self.submenuProvideFeedback)
        self.menuHelp.addAction(self.submenuAbout)
        self.menubar.addAction(self.menuMain.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "guteluft.jade-hs.de", None))
        self.label.setText(_translate("MainWindow", "This section is to view a data of guteluft.jade-hs.de", None))
        self.label_2.setText(_translate("MainWindow", "Chose the room:", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "H-I-07", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "H-I-10", None))
        self.comboBox.setItemText(2, _translate("MainWindow", "H-I-21", None))
        self.pushButton.setText(_translate("MainWindow", "Get help!", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGuteLuft), _translate("MainWindow", "guteluft.jade-hs.de", None))
        self.label_4.setText(_translate("MainWindow", "This section is to view a data of CO2-Ampel", None))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"justify\">We will train here to control Device via Tango. For training aims, the MySQL Tango-Database(Tango Server) must be configured on some computer.  &quot;Tango Device Server&quot; - just Raspberry controlling LEDS. </p></body></html>", None))
        self.pushButtonControlCO2Ampel.setText(_translate("MainWindow", "Test \"Control Device\"", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.TabCO2Ampel), _translate("MainWindow", "CO2-Ampel", None))
        self.checkBoxTemperatur.setText(_translate("MainWindow", "Temperatur", None))
        self.checkBoxHumidity.setText(_translate("MainWindow", "Humidity", None))
        self.labelInfo.setText(_translate("MainWindow", "Live visualisation of Data from device:", None))
        self.LabelInfo.setText(_translate("MainWindow", "____", None))
        self.menuMain.setTitle(_translate("MainWindow", "Main", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.submenuProvideFeedback.setText(_translate("MainWindow", "Provide feedback", None))
        self.submenuAbout.setText(_translate("MainWindow", "About", None))

